name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NODE_ENV: development

jobs:
  validate:
    name: Validate the changes
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 📦 Init Node, pnpm
        uses: ./.github/workflows/actions/init

      - name: ✅ Run validation
        run: pnpm run lint

      - name: ✅ Run build
        run: pnpm run build
